### ISSUE TITLE
ATmega32U2 EEPROM writing limits

### ISSUE THREAD

**Issue by 3d-gussner** [jacopotediosi/Octoprint-PrusaResetMode#1]
Please update the readme.

1. Changing the USB reset mode writes to the ATmel 32u2 eeprom which has a limit (even it is high, you should mention it.) 
2. When the USB reset is disabled on MK3/S/+ firmware updates via PrusaSlicer will fail as it needs a reboot to write to the xflash.
3. Read FW version is bit misleading as you only read the 32u2 firmware version and not he Printer firmware, here you can use  the gcode "PRUSA Fir"

**Comment by jacopotediosi** [comment]
Thanks so much for the suggestions!
I fixed these points with Release v0.1.1.

1. With commit 331ac9d9822994734ec02da754ad93dcf73dbfb2 I added a section to the README that informs about the writing limits of the ATmega32U2.

2. The recommendation to reactivate Reset Mode to update the printer was already present in the README and the confirmation messages also remind the user of this when clicking the buttons in the OctoPrint tab.

3. Commit a212798c819462978ac32548eac8d492ef1f1d26 modifies the UI to make it clearer that the button to read the FW version refers to the ATmega32U2 and not to the printer.
